services:
  studyxp-database:
    image: mysql:8.0
    container_name: studyxp-mysql-db
    environment:
      MYSQL_DATABASE: studyxp
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - studyxp-db-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  studyxp-app:
    build: ./backend
    container_name: studyxp-app

    depends_on:
      studyxp-database:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  studyxp-db-data: